<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        // Resolve category id dynamically or insert fallback if not existing (e.g., in unit tests)
        $bajuCatId = DB::table('service_categories')->where('slug', 'baju')->value('id');
        if (!$bajuCatId) {
            $bajuCatId = DB::table('service_categories')->insertGetId([
                'name' => 'Khusus Baju',
                'slug' => 'baju',
                'description' => 'Sewa baju satuan atau paket',
                'icon' => 'bi-bag-check-fill',
                'sort_order' => 4,
            ]);
        }

        $items = [
            // Premium
            [
                'category_id' => $bajuCatId,
                'code' => 'PKG-BAJU-MEL-PREM',
                'name' => 'Baju Melayu Premium',
                'slug' => 'baju-melayu-premium',
                'description' => 'Sewa Baju Melayu Premium',
                'price' => 1200000,
                'dp_amount' => 500000,
                'quota_per_day' => 3,
                'is_popular' => false,
                'image' => 'images/baju14.jpeg',
                'sort_order' => 10,
                'butuh_makeup' => false,
                'butuh_baju' => true,
                'softlens_wajib_pilih' => false,
                'status' => 'aktif',
            ],
            [
                'category_id' => $bajuCatId,
                'code' => 'PKG-BAJU-AKAD-GAUN-PREM',
                'name' => 'Baju Akad Gaun Premium',
                'slug' => 'baju-akad-gaun-premium',
                'description' => 'Sewa Baju Akad Gaun Premium',
                'price' => 1800000,
                'dp_amount' => 500000,
                'quota_per_day' => 3,
                'is_popular' => false,
                'image' => 'images/baju12.jpeg',
                'sort_order' => 11,
                'butuh_makeup' => false,
                'butuh_baju' => true,
                'softlens_wajib_pilih' => false,
                'status' => 'aktif',
            ],
            [
                'category_id' => $bajuCatId,
                'code' => 'PKG-BAJU-AKAD-KOTO-PREM',
                'name' => 'Baju Akad / Koto Gadang Premium',
                'slug' => 'baju-akad-koto-gadang-premium',
                'description' => 'Sewa Baju Akad / Koto Gadang Premium',
                'price' => 2000000,
                'dp_amount' => 500000,
                'quota_per_day' => 3,
                'is_popular' => false,
                'image' => 'images/baju10.jpeg',
                'sort_order' => 12,
                'butuh_makeup' => false,
                'butuh_baju' => true,
                'softlens_wajib_pilih' => false,
                'status' => 'aktif',
            ],
            [
                'category_id' => $bajuCatId,
                'code' => 'PKG-BAJU-MALAM-TANDUAK-PREM',
                'name' => 'Baju Malam / Tanduak / Solok Premium',
                'slug' => 'baju-malam-tanduak-solok-premium',
                'description' => 'Sewa Baju Malam / Tanduak / Solok Premium',
                'price' => 2000000,
                'dp_amount' => 500000,
                'quota_per_day' => 3,
                'is_popular' => false,
                'image' => 'images/baju11.jpeg',
                'sort_order' => 13,
                'butuh_makeup' => false,
                'butuh_baju' => true,
                'softlens_wajib_pilih' => false,
                'status' => 'aktif',
            ],
            [
                'category_id' => $bajuCatId,
                'code' => 'PKG-BAJU-BASUNTIANG-SUNTIANG-PREM',
                'name' => 'Baju Basuntiang Premium + Suntiang Premium',
                'slug' => 'baju-basuntiang-premium-suntiang-premium',
                'description' => 'Sewa Baju Basuntiang Premium + Suntiang Premium',
                'price' => 2500000,
                'dp_amount' => 500000,
                'quota_per_day' => 3,
                'is_popular' => false,
                'image' => 'images/baju4.jpeg',
                'sort_order' => 14,
                'butuh_makeup' => false,
                'butuh_baju' => true,
                'softlens_wajib_pilih' => false,
                'status' => 'aktif',
            ],
            [
                'category_id' => $bajuCatId,
                'code' => 'PKG-BAJU-BASUNTIANG-SUNTIANG-MELATI-PREM',
                'name' => 'Baju Basuntiang Premium + Suntiang Premium Depan Belakang + Melati Depan Belakang',
                'slug' => 'baju-basuntiang-premium-suntiang-depan-belakang-melati-depan-belakang',
                'description' => 'Sewa Baju Basuntiang Premium + Suntiang Premium Depan Belakang + Melati Depan Belakang',
                'price' => 3000000,
                'dp_amount' => 500000,
                'quota_per_day' => 3,
                'is_popular' => false,
                'image' => 'images/baju5.jpeg',
                'sort_order' => 15,
                'butuh_makeup' => false,
                'butuh_baju' => true,
                'softlens_wajib_pilih' => false,
                'status' => 'aktif',
            ],
            // Luxury
            [
                'category_id' => $bajuCatId,
                'code' => 'PKG-BAJU-MEL-LUX',
                'name' => 'Baju Melayu Luxury',
                'slug' => 'baju-melayu-luxury',
                'description' => 'Sewa Baju Melayu Luxury',
                'price' => 1500000,
                'dp_amount' => 500000,
                'quota_per_day' => 3,
                'is_popular' => false,
                'image' => 'images/baju13.jpeg',
                'sort_order' => 16,
                'butuh_makeup' => false,
                'butuh_baju' => true,
                'softlens_wajib_pilih' => false,
                'status' => 'aktif',
            ],
            [
                'category_id' => $bajuCatId,
                'code' => 'PKG-BAJU-AKAD-GAUN-LUX',
                'name' => 'Baju Akad Gaun Luxury',
                'slug' => 'baju-akad-gaun-luxury',
                'description' => 'Sewa Baju Akad Gaun Luxury',
                'price' => 2300000,
                'dp_amount' => 500000,
                'quota_per_day' => 3,
                'is_popular' => false,
                'image' => 'images/baju9.jpeg',
                'sort_order' => 17,
                'butuh_makeup' => false,
                'butuh_baju' => true,
                'softlens_wajib_pilih' => false,
                'status' => 'aktif',
            ],
            [
                'category_id' => $bajuCatId,
                'code' => 'PKG-BAJU-AKAD-KEBAYA-LUX',
                'name' => 'Baju Akad Kebaya Luxury',
                'slug' => 'baju-akad-kebaya-luxury',
                'description' => 'Sewa Baju Akad Kebaya Luxury',
                'price' => 2500000,
                'dp_amount' => 500000,
                'quota_per_day' => 3,
                'is_popular' => false,
                'image' => 'images/baju8.jpeg',
                'sort_order' => 18,
                'butuh_makeup' => false,
                'butuh_baju' => true,
                'softlens_wajib_pilih' => false,
                'status' => 'aktif',
            ],
            [
                'category_id' => $bajuCatId,
                'code' => 'PKG-BAJU-BASUNTIANG-SUNTIANG-LUX',
                'name' => 'Baju Basuntiang Luxury + Suntiang Premium',
                'slug' => 'baju-basuntiang-luxury-suntiang-premium',
                'description' => 'Sewa Baju Basuntiang Luxury + Suntiang Premium',
                'price' => 3000000,
                'dp_amount' => 500000,
                'quota_per_day' => 3,
                'is_popular' => false,
                'image' => 'images/baju6.jpeg',
                'sort_order' => 19,
                'butuh_makeup' => false,
                'butuh_baju' => true,
                'softlens_wajib_pilih' => false,
                'status' => 'aktif',
            ],
            [
                'category_id' => $bajuCatId,
                'code' => 'PKG-BAJU-BASUNTIANG-SUNTIANG-MELATI-LUX',
                'name' => 'Baju Basuntiang Luxury + Suntiang Premium Depan Belakang + Melati Depan Belakang',
                'slug' => 'baju-basuntiang-luxury-suntiang-depan-belakang-melati-depan-belakang',
                'description' => 'Sewa Baju Basuntiang Luxury + Suntiang Premium Depan Belakang + Melati Depan Belakang',
                'price' => 3500000,
                'dp_amount' => 500000,
                'quota_per_day' => 3,
                'is_popular' => false,
                'image' => 'images/baju7.jpeg',
                'sort_order' => 20,
                'butuh_makeup' => false,
                'butuh_baju' => true,
                'softlens_wajib_pilih' => false,
                'status' => 'aktif',
            ],
            // Others / Accessories
            [
                'category_id' => $bajuCatId,
                'code' => 'PKG-SUNTIANG-PREM',
                'name' => 'Suntiang Premium',
                'slug' => 'suntiang-premium',
                'description' => 'Sewa Suntiang Premium',
                'price' => 800000,
                'dp_amount' => 500000,
                'quota_per_day' => 3,
                'is_popular' => false,
                'image' => null,
                'sort_order' => 21,
                'butuh_makeup' => false,
                'butuh_baju' => true,
                'softlens_wajib_pilih' => false,
                'status' => 'aktif',
            ],
            [
                'category_id' => $bajuCatId,
                'code' => 'PKG-SUNTIANG-ACC-PREM',
                'name' => 'Suntiang Premium + Acc',
                'slug' => 'suntiang-premium-acc',
                'description' => 'Sewa Suntiang Premium + Acc',
                'price' => 1000000,
                'dp_amount' => 500000,
                'quota_per_day' => 3,
                'is_popular' => false,
                'image' => null,
                'sort_order' => 22,
                'butuh_makeup' => false,
                'butuh_baju' => true,
                'softlens_wajib_pilih' => false,
                'status' => 'aktif',
            ],
            [
                'category_id' => $bajuCatId,
                'code' => 'PKG-SUNTIANG-BELAKANG-ACC-PREM',
                'name' => 'Suntiang Premium + Belakang + Acc',
                'slug' => 'suntiang-premium-belakang-acc',
                'description' => 'Sewa Suntiang Premium + Belakang + Acc',
                'price' => 1300000,
                'dp_amount' => 500000,
                'quota_per_day' => 3,
                'is_popular' => false,
                'image' => null,
                'sort_order' => 23,
                'butuh_makeup' => false,
                'butuh_baju' => true,
                'softlens_wajib_pilih' => false,
                'status' => 'aktif',
            ],
            [
                'category_id' => $bajuCatId,
                'code' => 'PKG-SUNTIANG-BELAKANG-ACC-MELATI-PREM',
                'name' => 'Suntiang Premium + Belakang + Acc + Melati Depan Belakang',
                'slug' => 'suntiang-premium-belakang-acc-melati-depan-belakang',
                'description' => 'Sewa Suntiang Premium + Belakang + Acc + Melati Depan Belakang',
                'price' => 1700000,
                'dp_amount' => 500000,
                'quota_per_day' => 3,
                'is_popular' => false,
                'image' => null,
                'sort_order' => 24,
                'butuh_makeup' => false,
                'butuh_baju' => true,
                'softlens_wajib_pilih' => false,
                'status' => 'aktif',
            ],
            [
                'category_id' => $bajuCatId,
                'code' => 'PKG-MELATI-DEPAN-BELAKANG',
                'name' => 'Melati Depan Belakang',
                'slug' => 'melati-depan-belakang-satuan',
                'description' => 'Sewa Melati Depan Belakang',
                'price' => 450000,
                'dp_amount' => 450000,
                'quota_per_day' => 3,
                'is_popular' => false,
                'image' => null,
                'sort_order' => 25,
                'butuh_makeup' => false,
                'butuh_baju' => true,
                'softlens_wajib_pilih' => false,
                'status' => 'aktif',
            ],
            [
                'category_id' => $bajuCatId,
                'code' => 'PKG-JASA-PASANG-SUNTIANG',
                'name' => 'Jasa Pemasangan Suntiang',
                'slug' => 'jasa-pemasangan-suntiang',
                'description' => 'Jasa Pemasangan Suntiang untuk daerah Lubuk Alung, Padang Pariaman, Pariaman',
                'price' => 250000,
                'dp_amount' => 250000,
                'quota_per_day' => 3,
                'is_popular' => false,
                'image' => null,
                'sort_order' => 26,
                'butuh_makeup' => false,
                'butuh_baju' => true,
                'softlens_wajib_pilih' => false,
                'status' => 'aktif',
            ]
        ];

        foreach ($items as $item) {
            DB::table('service_packages')->updateOrInsert(
                ['code' => $item['code']],
                $item
            );
        }
    }

    public function down(): void
    {
        $codes = [
            'PKG-BAJU-MEL-PREM',
            'PKG-BAJU-AKAD-GAUN-PREM',
            'PKG-BAJU-AKAD-KOTO-PREM',
            'PKG-BAJU-MALAM-TANDUAK-PREM',
            'PKG-BAJU-BASUNTIANG-SUNTIANG-PREM',
            'PKG-BAJU-BASUNTIANG-SUNTIANG-MELATI-PREM',
            'PKG-BAJU-MEL-LUX',
            'PKG-BAJU-AKAD-GAUN-LUX',
            'PKG-BAJU-AKAD-KEBAYA-LUX',
            'PKG-BAJU-BASUNTIANG-SUNTIANG-LUX',
            'PKG-BAJU-BASUNTIANG-SUNTIANG-MELATI-LUX',
            'PKG-SUNTIANG-PREM',
            'PKG-SUNTIANG-ACC-PREM',
            'PKG-SUNTIANG-BELAKANG-ACC-PREM',
            'PKG-SUNTIANG-BELAKANG-ACC-MELATI-PREM',
            'PKG-MELATI-DEPAN-BELAKANG',
            'PKG-JASA-PASANG-SUNTIANG'
        ];

        DB::table('service_packages')->whereIn('code', $codes)->delete();
    }
};
